import AboutusSection from "@/components/About-us-section";
import Banner from "@/components/Banner";
import Donate from "@/components/Donate";
import DownlaodSection from "@/components/Download-section";
import Events from "@/components/Events";
import Services from "@/components/services";
import { Box } from "@mui/material";
import Head from "next/head";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Banner />
        <Box sx={{ mt: 10 }}>
          <AboutusSection />
        </Box>
        <Box sx={{ mt: 10 }}>
          <Services />
        </Box>
        {/* <Box sx={{ mt: 10 }}>
          <DownlaodSection />
        </Box> */}
        <Box sx={{ mt: 10 }}>
          <Donate />
        </Box>
        <Box sx={{ mt: 10 }}>
          <Events />
        </Box>
      </Box>
    </>
  );
}
